---
repository: https://github.com/timoguic/acit4640-py-mysql.git
db_user: root
db_pass: password
app_user: backend
app_pass: securepassword
app_host: terraform-20231211080022387300000005.cbimu9mjowgg.us-west-1.rds.amazonaws.com
