---
- name: Install tools and setup nginx
  ansible.builtin.package:
    update_cache: true
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - nginx
    - zip
    - unzip
    - net-tools
    - nmap

- name: rm repository if exitst
  become: true
  ansible.builtin.shell: |
    sudo rm -rf /home/ubuntu/app

- name: Clone on frontend 
  become: true
  git:
    repo: "{{ repository }}"
    dest: /home/ubuntu/app

- name: Remove Nginx default file
  become: true
  ansible.builtin.shell: |
    sudo rm -f /etc/nginx/sites-enabled/default

- name: Remove index.html file
  become: true
  ansible.builtin.shell: |
    sudo rm -f /home/ubuntu/app/frontend/index.html

- name: Setup nginx conf file
  become: true
  template:
    src: ./templates/default
    dest: "{{ nginx_conf_path }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644' 
     
- name: Setup index.html file
  become: true
  template:
    src: ./templates/index.html
    dest: /home/ubuntu/app/frontend/index.html
    owner: ubuntu
    group: ubuntu
    mode: '0777'

- name: Setup file permissions
  become: true
  ansible.builtin.shell: |
    chown -R www-data /home/ubuntu/app/frontend
    sudo chmod 755 /home
    sudo chmod 755 /home/ubuntu
    sudo chmod 755 /home/ubuntu/app
    sudo -R chmod 755 /home/ubuntu/app/frontend
    sudo chown www-data:www-data /home/ubuntu/app/frontend
    sudo chown www-data:www-data /home/ubuntu/app/frontend/index.html

  
  
- name: Restart and enable nginx service
  become: true
  service:
    name: nginx
    state: restarted
    enabled: yes
